### ISSUE TITLE
Create a CockroachCloud Cluster Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#9989] opened 2021-03-15 15:20 UTC
Re: [Create a CockroachCloud Cluster](https://cockroachlabs.com/docs/cockroachcloud/create-your-cluster.html)

## Issue Description
update this doc with iops per cloud provider

## Suggested Resolution 
adding IOPs to the page would make a welcome addition.

**Comment by lnhsingh** [comment] 2021-03-15 16:04
Closing - dupe of CC-3698

**Closed by lnhsingh** 2021-03-15 16:04 UTC
