### ISSUE TITLE
Window functions appear under "Aggregate functions" in 19.2 docs

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/docs#7236] opened 2020-04-28 13:39 UTC
The list of aggregate functions was inadvertently replaced with the list of windows functions in 869faab6148b5caa8812452bff1086d7ff761109.

Compare https://www.cockroachlabs.com/docs/v19.1/functions-and-operators.html#aggregate-functions and https://www.cockroachlabs.com/docs/v19.2/functions-and-operators.html#aggregate-functions.

**Comment by Shiwanee** [comment] 2020-09-18 16:32
@Amruta-Ranade , Could you please assign this to me?

**Comment by Amruta-Ranade** [comment] 2020-09-18 17:30
@Shiwanee Since you already have an issue assigned to you, I'd like other participants to have a shot at this one. Feel free to check back in a few days to see if the issue is still available :)

**Comment by Shiwanee** [comment] 2020-09-18 17:49
@Amruta-Ranade , Sure!
Thanks,
Shiwanee

**Comment by Shiwanee** [comment] 2020-09-25 16:34
@Amruta-Ranade I was just checking back as Hacktoberfest is now around the corner :-)

**Comment by Amruta-Ranade** [comment] 2020-09-25 16:59
Oh, I meant check back in mid-October 😄 I need time to publicize the issues and want to give folks time to evaluate.

**Comment by jseldess** [comment] 2020-09-27 05:08
This is better for an internal writer, @Amruta-Ranade, since it relates to the way we include auto-generated content from the cockroach repo.

**Closed** 2020-09-28 18:34 UTC
Labels: A-sql, C-improvement, O-external, T-incorrect-or-unclear-info
