### ISSUE TITLE
Secure build a Go app

### ISSUE THREAD

**Issue by AJCStriker** [cockroachdb/docs#1409] opened 2017-05-13 21:20 UTC
The documentation does not currently layout any mechanism for using either of the provided Go drivers with the client TLS authentication mechanisms explained in the "secure cluster" sections of the video.

Taking as an assumption that running an insecure cluster in production would be irresponsible I feel that it would be beneficial to adapt the driver explanations to cover how to use the TLS client certificates within a postgres client driver.

Or simply referring to the use of Passwords as a fallback in the case that the driver does not natively support such a mechanism.

**Comment by jseldess** [comment] 2017-05-13 23:12
Thanks for opening this issue, @AJCStriker. It's on our near-term plan to provide secure versions of the build an app tutorials. Here's the main issue, in case you want track progress: https://github.com/cockroachdb/docs/issues/631

**Comment by jseldess** [comment] 2018-02-25 07:28
Duplicate of https://github.com/cockroachdb/docs/issues/631

**Closed by jseldess** 2018-02-25 07:28 UTC
Labels: community, enhancement
