### ISSUE TITLE
builtins: implement regr_avgy

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9572] opened 2021-01-29 19:35 UTC
PR: https://github.com/cockroachdb/cockroach/pull/57583

From release notes:
> Implemented `regr_avgy` [builtin](../v21.1/functions-and-operators.html#built-in-functions) aggregation function. [#57583][#57583] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment] 2021-02-11 21:08
duplicate of https://github.com/cockroachdb/docs/issues/9562

**Closed by ericharmeling** 2021-02-11 21:08 UTC
Labels: A-sql, C-release-note, P-1
