### ISSUE TITLE
Update host ports for nodes 2 and 3 in Start a Cluster in Docker (Insecure) doc

### ISSUE THREAD

**Issue by chucklqsun** [cockroachdb/docs#8463] opened 2020-09-24 08:41 UTC
Exalate commented:

Re: [Start a Cluster in Docker (Insecure)](https://cockroachlabs.com/docs//v20.1/start-a-local-cluster-in-docker-windows.html)

## Issue Description
Start two more nodes: (roach2 and roach3)
.....
-p 26257:26257 -p 8080:8080  `
.....
conflict with roarch1. It will throws error when starting the nodes.

## Suggested Resolution 
remove the port mapping for roach2 and roach3

Jira Issue: DOC-782

**Comment by lestercheung** [comment] 2020-09-24 08:45
Or use different host ports (so you can still connect to roach2 and 3 if you decide to kill roach1 for demos).

**Comment by lnhsingh** [comment] 2020-09-24 22:57
@taroface I assigned to you but this might be a `good-first-issue` if you can provide the changes that need to be made. Feel free to unassign and add the label if you think so.

**Comment by taroface** [comment] 2020-09-24 23:03
Hmm I feel this needs some investigation into what our recommended best practice will be. I will save it for my queue!

**Comment by rafiss** [comment] 2020-09-25 22:01
This looks like a duplicate of #7199

**Closed** 2024-02-07 00:48 UTC
Labels: O-external, T-something-broken, P-3, C-doc-improvement
