### ISSUE TITLE
[NH] Vectorization: Data Types

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5970] opened 2019-11-26 22:03 UTC
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/reciDxEVXj4Y68MCz

Description: Allows the SQL Vectorization Engine to work with more data types. SQL Vectorized Execution now works with the following data types:
Timestamp
UUID

Team: Andrew Woods, Jordan Lewis

**Comment by ericharmeling** [comment] 2019-12-12 18:20
This is a duplicate of https://github.com/cockroachdb/docs/issues/5917.

Fixed with https://github.com/cockroachdb/docs/pull/6107.

**Closed by ericharmeling** 2019-12-12 18:20 UTC
Labels: A-sql, C-roadmap
