### ISSUE TITLE
Faulty link formatting on "Production Checklist Doc Update" page

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#7180] opened 2020-04-16 21:56 UTC
Look around "NUMA](https://en.wikipedia.org/wiki/Non-uniform_memory_access)(non-uniform memory access)", we missed a brace somewhere.

**Comment by Shiwanee** [comment] 2020-09-18 16:42
@Amruta-Ranade , Could you please assign this issue to me?

**Comment by Amruta-Ranade** [comment] 2020-09-18 17:30
@Shiwanee Since you already have an issue assigned to you, I'd like other participants to have a shot at this one. Feel free to check back in a few days to see if the issue is still available :)

**Comment by Shiwanee** [comment] 2020-09-18 17:49
@Amruta-Ranade , Sure!
Thanks,
Shiwanee

**Comment by Shiwanee** [comment] 2020-09-25 16:34
@Amruta-Ranade I was just checking back as Hacktoberfest is now around the corner :-)

**Comment by Amruta-Ranade** [comment] 2020-09-25 16:59
Oh, I meant check back in mid-October 😄 I need time to publicize the issues and want to give folks time to evaluate them.

**Comment by jseldess** [comment] 2020-09-27 05:05
This issue is out-dated. The issue was fixed in the meantime.

**Closed by jseldess** 2020-09-27 05:05 UTC
Labels: good-first-issue

**Comment by Shiwanee** [comment] 2020-10-01 00:05
@Amruta-Ranade Okay! I think I am too excited for Hacktoberfest! 😄 This is my first time and so was not aware of timelines for publishing the issues and way they are assigned! Sorry about that. 
If you think I can take up any other issues in future, please feel free to assign them to me. I would like to work on all 4(+) issues from Cockroach Labs for Hacktoberfest :-)
