### ISSUE TITLE
Make it explicit that you can import multiple CSV files

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#3911] opened 2018-10-24 15:39 UTC
I ran into this with @drewdeally and a customer the other day -- when you run IMPORT TABLE ... CSV DATA (...), you can list multiple import files separated by commas, but the documentation currently doesn't make this obvious. We should specify in the [IMPORT statement documentation](https://www.cockroachlabs.com/docs/v2.1/import.html) and the [Migrate from CSV](https://www.cockroachlabs.com/docs/v2.1/migrate-from-csv.html) guide that you can specify multiple files. (Drive-by nit: we should also fix the railroad diagram for the IMPORT statement so it fits on the page correctly.)

**Comment by jseldess** [comment] 2018-10-24 15:45
Thanks, @rolandcrosby. This is a duplicate of https://github.com/cockroachdb/docs/issues/3101, which @Amruta-Ranade has on her plate.

**Closed by jseldess** 2018-10-24 15:45 UTC

**Comment by rolandcrosby** [comment] 2018-10-24 15:49
D'oh, thanks Jesse and Amruta!
