### ISSUE TITLE
decommission: test concurrent node decommission

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#3185] opened 2018-05-23 12:07 UTC
While replacing all nodes on `register`, I went a bit overboard and ended up marking four nodes for decommission at the same time. This severely wedged the cluster with failed node liveness for all nodes until I managed to recommission two of the 4 nodes.

We should test this further (2/3/4 nodes being decommissioned at a time), and adjust docs as needed.

CC: @jseldess, @nstewart (product experience), @tschottdorf (I believe is the decom expert)

**Comment by tschottdorf** [comment] 2018-05-23 12:26
Duplicate of https://github.com/cockroachdb/cockroach/issues/25131.

**Closed by tschottdorf** 2018-05-23 12:26 UTC
