### ISSUE TITLE
Certificate Revocation Support

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3995] opened 2018-11-05 04:19 UTC
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recjB8fKRH3DxSLYY
PM: @rolandcrosby 
Eng: @mberhault

**Comment by jseldess** [comment] 2018-12-18 20:55
Moved out of scope for 2.2.

**Comment by Amruta-Ranade** [comment] 2020-09-15 15:39
Duplicate of https://github.com/cockroachdb/docs/issues/8285

**Closed by Amruta-Ranade** 2020-09-15 15:39 UTC
Labels: A-cloud, A-siam, C-roadmap
