### ISSUE TITLE
Panic when regenerating sql diagrams

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2273] opened 2017-12-11 22:00 UTC
```
~/src/github.com/cockroachdb/docs/generate$ go run main.go --filter create_sequence_stmt
2017/12/11 16:21:57 generate BNF: https://raw.githubusercontent.com/cockroachdb/cockroach/master/pkg/sql/parser/sql.y
processing statement "create_sequence_stmt"...
2017/12/11 16:21:58 parse: create_sequence_stmt, inline: [], descend: false
panic: signed_iconst64

goroutine 50 [running]:
github.com/cockroachdb/docs/generate/extract.ParseGrammar(0x15c7a40, 0xc42042cab0, 0xc42003b920, 0x3, 0x3)
	/Users/jesseseldess/src/github.com/cockroachdb/docs/generate/extract/extract.go:228 +0xed7
main.runParse(0x15c7a40, 0xc42042cab0, 0x0, 0x0, 0x0, 0x13d56d3, 0x14, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/docs/generate/main.go:784 +0x194
main.main.func7.3(0xc42027bb80, 0xc420076360, 0xc42032c060, 0xc420016585, 0xc420040cc0, 0xc420040ca0, 0x13d56d3, 0x14, 0x13d56d3, 0x14, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/docs/generate/main.go:697 +0x20a
created by main.main.func7
	/Users/jesseseldess/src/github.com/cockroachdb/docs/generate/main.go:690 +0x724f
exit status 2
```

**Comment by mjibson** [comment] 2017-12-11 22:09
This was caused by #19664 which uses lowercase iconst instead of ICONST, so the parser doesn't think it's an identifier. We should 1) switch the iconst to ICONST and 2) run docgen in a no-output mode so we can verify it at least parser sql.y to prevent this kind of problem in the future.

**Comment by mjibson** [comment] 2017-12-12 08:48
Note: my initial prescription was wrong. Just needed to support numbers in expr names.

**Comment by dt** [comment] 2017-12-12 14:56
@mjibson yeah, for point 2), that was the goal of moving it into the main repo -- just need to pick that back up. maybe for now, even if we don't switch to an open source generator right away, we should generate and check in the BNF in the main repo, then have the process be to generate the diagrams in docs from the main repo's BNF files

**Comment by jseldess** [comment] 2017-12-12 20:15
Sounds good to me. That would allows us to remove the generation files from the docs repo, right? I'd just need help documenting the correct commands.

**Comment by jseldess** [comment] 2017-12-13 15:05
@mjibson and @dt, FYI, for next Monday's alpha release, I'm renaming the `v1.2` directory to `v2.0`. I'll also update `generate/main.go` and `generate/funcs.go` to use `v2.0`. We'll need to make the same change to the generators in the `cockroach` repo.

**Closed** 2017-12-18 20:06 UTC
Labels: bug
