### ISSUE TITLE
Start `cockroach` as a service

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1543] opened 2017-06-08 18:50 UTC
Integrate steps to have CockroachDB run as a service on *nix OSes.

**Comment by thomasmodeneis** [comment] 2018-06-11 16:30
Is this going to happen sometime soon ?
Its really not nice to have to control cockroach start without proper service management.

**Comment by jseldess** [comment] 2018-06-11 19:06
@thomasmodeneis, we're currently working on adding `systemd` service support to our deployment tutorials. You can take an early look here if you like: https://github.com/cockroachdb/docs/pull/3163.

I'm going to close this issue as a duplicate of https://github.com/cockroachdb/docs/issues/1772.

**Closed by jseldess** 2018-06-11 19:06 UTC
Labels: enhancement
