### ISSUE TITLE
After clicking on an anchored section title, the top of the section is cut off by the new Managed CockroachDB doc selector

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#4019] opened 2018-11-05 19:19 UTC
For example, on the https://www.cockroachlabs.com/docs/stable/kubernetes-performance.html page, if I click on one of the headings such as "Disk type", it moves me down the page such that it looks like this:

<img width="1379" alt="screen shot 2018-11-05 at 11 16 17 am" src="https://user-images.githubusercontent.com/7085343/48021057-771b9480-e0ec-11e8-9589-ba3ae6463956.png">

As you can see, the "Disk type" title text is covered up by the horizontal bar at the top of the section. It'd be much nicer if it instead looked like this after the scroll:

<img width="1368" alt="screen shot 2018-11-05 at 11 18 08 am" src="https://user-images.githubusercontent.com/7085343/48021095-8f8baf00-e0ec-11e8-8f67-1eadbce3ba3f.png">

@j-low

**Comment by jseldess** [comment] 2018-11-09 15:39
Thanks, @a-robinson. This is a known issue that @j-low is planning to fix, but thank you for creating an issue for it.

**Comment by jseldess** [comment] 2018-11-12 03:07
Just realized this is a dupe of https://github.com/cockroachdb/docs/issues/1451.

**Closed by jseldess** 2018-11-12 03:07 UTC
Labels: A-docs-infrastructure, C-something-broken
