### ISSUE TITLE
Start a Local Cluster (Insecure) Doc Update 

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#9240] opened 2020-12-28 16:44 UTC
Re: [Start a Local Cluster (Insecure)](https://cockroachlabs.com/docs//v20.2/start-a-local-cluster.html)

## Issue Description

The instructions reference the ```cockroach quit``` command, which is [deprecated](https://www.cockroachlabs.com/docs/dev/cockroach-quit.html).
Running this command produces the following message:

```
Command "quit" is deprecated, see 'cockroach node drain' instead to drain a 
server without terminating the server process (which can in turn be done using 
an orchestration layer or a process manager, or by sending a termination signal
directly).
```

## Suggested Resolution 

First, for these instructions, decide whether draining the server process before terminating the server process is necessary.  The [docs](https://www.cockroachlabs.com/docs/dev/cockroach-quit.html) seem to indicate that, when shutting down a node, draining happens automatically without it being necessary to manually drain the server process first.

Second, for these instructions, decide the best way to stop the server process.  Since, in these instructions, the server process was started from the command line, it seems appropriate to use the ```kill``` command to stop the server process.   That is the approach suggested below, but the doc discusses other approaches, such as using a process manager.

If the manual drain is necessary, then replace references to ```cockroach quit``` with the sequence: 
1. ```cockroach drain```
1. determine the process ID, presumably using the ```ps``` command
1. issue the ```kill``` command for the process ID determined above

If the manual drain is not necessary, then replace references to ```cockroach quit``` with just steps #&#x2060;2 and #&#x2060;3 above.

Screen shots:

<img width="1433" alt="cockroach quit command is deprecated 2020-12-23" src="https://user-images.githubusercontent.com/76179780/103229310-c93d5680-4900-11eb-9821-7220fa3a667a.png">

<img width="1430" alt="cockroach quit command is deprecated 2020-12-23b" src="https://user-images.githubusercontent.com/76179780/103229344-d0646480-4900-11eb-95cb-6758e899f1fb.png">

**Comment by jseldess** [comment] 2021-02-28 01:47
Duplicate of https://github.com/cockroachdb/docs/issues/9261

**Closed by jseldess** 2021-02-28 01:47 UTC
