### ISSUE TITLE
Search: Add code and table text

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#7107] opened 2020-04-09 15:20 UTC
from Florence:
>  Search in docs does not find text formatted as Code. For example, search for `kv.range_split.load_qps_threshold` (or any other cluster setting) does not find the instance on [this page ](https://www.cockroachlabs.com/docs/stable/cluster-settings.html).

Also, text within a table should be added too.

**Comment by jseldess** [comment] 2020-04-25 03:59
Assigning this to @yingzhuchin's product ops backlog.

**Comment by yingzhuchin** [comment] 2020-04-27 22:13
Upon digging, I've realized this is not as straightforward as I assumed. The issue is not with text formatted as code per se, nor with text within a table. If you search `startrek` for example, you will notice that the top result returns precisely text formatted as code and situated within a table. (https://www.cockroachlabs.com/docs/search.html?query=startrek)

The issue is rather that certain pages *include* other Markdown files from the `_includes` folder. Since files in `_include` are not themselves standalone pages displayed to end users, said files cannot easily be returned as part of search results.

**Comment by yingzhuchin** [comment] 2020-04-28 18:10
Eating my words again! I can't account for the inconsistency in search behavior (between `startrek` and `range_split` for example), but I was able to get table text included in results after explicitly asking Algolia to index table tags. See linked PR. I also had to adjust our max record size to make it work, but I think we're all set now.

**Closed** 2020-04-28 19:35 UTC
Labels: A-prod-ops, C-improvement, O-support, P-1
