### ISSUE TITLE
sql: separate "main" from "internal" metrics

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4260] opened 2019-01-15 20:24 UTC
PR: https://github.com/cockroachdb/cockroach/pull/32215

From release notes:
> CockroachDB now collects statistics for statements executed "internally" (for system purposes). This is meant to facilitate performance troubleshooting. [#32215][#32215] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment] 2019-01-28 20:43
Dupe of #4265

**Closed by rmloveland** 2019-01-28 20:43 UTC
Labels: A-sql, O-release-note, P-1, ready
