### ISSUE TITLE
change in CHAR(n) padding behavior is undocumented

### ISSUE THREAD

**Issue by osmes** [cockroachdb/docs#10499] opened 2021-05-04 20:12 UTC
CHAR(n) columns pad to the right to n length as of 20.2.0-alpha.2 [1].  Documentation [2] indicates that there is no padding for all variants of STRING(n).  The bullet [3] should be updated to state the exception for CHAR(n) or an additional bullet should be added for clarification.

[1] https://www.cockroachlabs.com/docs/releases/v20.2.0-alpha.2
Previously, when streaming values from a column declared of type char(n), the length of the value could be <= n. Now all values streamed have length exactly n by padding spaces to the right if necessary. #49886

[2] https://www.cockroachlabs.com/docs/v20.2/string#length

[3] If the value is under the column's length limit, CockroachDB does not add padding. This applies to STRING(n) and all its aliases.

**Comment by ianjevans** [comment] 2021-05-24 15:43
Duplicate of #10449.

**Closed** 2021-05-26 13:52 UTC
Labels: A-sql, O-support, T-incorrect-or-unclear-info, X-duplicate
