### ISSUE TITLE
Follow-up: CDC

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#3316] opened 2018-07-02 17:49 UTC
CDC was documented for 7/2 alpha and will need to be updated for v2.1:

- Add SQL reference docs + diagrams
- #3601
- #3602 
- #3603
- #3605 
- #3606

Added later:
- Add info on how to create a changefeed for partitions and specific rows
- Add example with load generator (nice to have?)
- Add info on how to use the core changefeed

Original issue: https://github.com/cockroachdb/docs/issues/2993
PR: https://github.com/cockroachdb/docs/pull/3308, https://github.com/cockroachdb/docs/pull/3418

**Comment by lhirata** [comment] 2018-07-23 20:13
See [Dan's notes](https://paper.dropbox.com/doc/Demos-for-Docs-CDC--AIXcDM8TcefxMgUFoem6C_1CAg-wp9YDiQiiierEmOVKXTvp)

**Comment by rolandcrosby** [comment] 2018-08-21 17:15
Some other CDC doc updates that we will want to make for the 2.1 release:
- CREATE CHANGEFEED ... WITH TIMESTAMPS has changed to WITH UPDATED (include updated timestamp in records) / WITH RESOLVED (periodically emit resolved timestamps to the changefeed) / WITH UPDATED, RESOLVED (do both)
- CREATE CHANGEFEED FOR DATABASE is not supported in 2.1 - for this release we will only support changefeeds for individual tables
- The second point in the [Ordering Guarantees](https://www.cockroachlabs.com/docs/v2.1/change-data-capture.html#ordering-guarantees) currently implies that previously-seen values (duplicates) can be sent out of order, but doesn't make that explicit. Here's how Dan explained that to me:
> you can see `k=a ts=1`, then `k=a ts=2` then `k=a ts=1` again
but you'll never see `k=a ts=2` then `k=a ts=1`
without seeing the `ts=1` first
so each emitted row sort of acts like a mini resolved timestamp
where once you see a row emitted at some time, you'll never see _previously unseen_ changes for that row at a lower timestamp

**Comment by lhirata** [comment] 2018-08-28 16:46
@rolandcrosby Can you help me understand the point about ordering guarantees? If I understand correctly, previously seen values can be sent out of order, but you'll never see a new change for that row at an earlier timestamp. Can you help me understand the example?

> You can see `k=a ts=1` then `k=a ts=2` then `k=a ts=1` again, but you'll never see `k=a ts=2 `then `k=a ts=1` without seeing `k=a ts=1` first.

Does this mean that `k=a ts=1` is a duplicate? So you will never see `k=a ts=2` without first seeing `ts=1` becuase `ts=1` is the earlier value?

 earlier value so you will never see `k=a ts=2` (the later value) without seeing the

**Comment by rolandcrosby** [comment] 2018-08-29 15:59
@lhirata That's right. To make this more concrete, if you ran something like this:

```sql
create table foo (id serial primary key, value string);
create changefeed for table foo into 'kafka://localhost:9092' with updated;
insert into foo values (1, 'value1');
update foo set value = 'value2' where id = 1;
```

you'd expect the changefeed to contain the following:

```
[1]	{"__crdb__": {"updated": "1535558012223402739.0000000000"}, "id": 1, "value": "value1"}
[1]	{"__crdb__": {"updated": "1535558022832467901.0000000000"}, "id": 1, "value": "value2"}
```

and this would also be a possible changefeed output (containing an out-of-order duplicate of an earlier value that you already saw):

```
[1]	{"__crdb__": {"updated": "1535558012223402739.0000000000"}, "id": 1, "value": "value1"}
[1]	{"__crdb__": {"updated": "1535558022832467901.0000000000"}, "id": 1, "value": "value2"}
[1]	{"__crdb__": {"updated": "1535558012223402739.0000000000"}, "id": 1, "value": "value1"}
```

but we do guarantee that you'll never get something like this (an out-of-order update that you never saw before):

```
[1]	{"__crdb__": {"updated": "1535558022832467901.0000000000"}, "id": 1, "value": "value2"}
[1]	{"__crdb__": {"updated": "1535558012223402739.0000000000"}, "id": 1, "value": "value1"}
```

**Comment by lhirata** [comment] 2018-08-30 14:33
From Roland: "We need to document the time format for WITH CURSOR - it’s an internal cluster timestamp and I don’t think we explicitly talk about the format anywhere. Dan or I can help if you need more details."

**Closed** 2018-09-20 17:56 UTC
Labels: follow-up, in progress, roadmap
