### ISSUE TITLE
sql: Add command to show range information about a row/rows

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5635] opened 2019-10-17 03:21 UTC
PR: https://github.com/cockroachdb/cockroach/pull/40954

From release notes:
> The new `SHOW RANGE ... FOR ROW` statement identifies the range containing a specific row of a table or secondary index. This is particularly useful for validating the location of a specific piece of data when using [partitions](../v19.2/topology-geo-partitioned-replicas.html) to control data location for improved performance or GDPR compliance. Note that this new statement is **experimental** and its interface and output are subject to change. [#40954][#40954] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment] 2019-10-17 13:59
This is a duplicate of #5534.

**Closed by ericharmeling** 2019-10-17 13:59 UTC
Labels: A-sql, C-release-note, P-1
