### ISSUE TITLE
sql: disable table renames across schemas

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8128] opened 2020-08-26 22:33 UTC
PR: https://github.com/cockroachdb/cockroach/pull/51433

From release notes:
> Added a deprecation notice for the use of [`ALTER TABLE .. RENAME`](../v20.2/alter-table.html) with a qualified name. [#51433][#51433] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment] 2020-08-27 13:39
Duplicate of #8129

**Closed by ericharmeling** 2020-08-27 13:39 UTC
Labels: A-sql, C-release-note, P-1
