### ISSUE TITLE
opt: support recursive CTEs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5909] opened 2019-11-21 14:53 UTC
PR: https://github.com/cockroachdb/cockroach/pull/41368

From release notes:
> Added support for `WITH RECURSIVE` with `UNION ALL`. [#41368][#41368] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment] 2020-01-09 16:03
Duplicate of #5956.

**Closed by ericharmeling** 2020-01-09 16:03 UTC
Labels: A-sql, C-release-note
