### ISSUE TITLE
Document the background growth of data in the cluster caused by timeseries data

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#1414] opened 2017-05-15 18:05 UTC
Apologies if we already mention this somewhere. There's two pieces of this that are confusing -- the increase of the live bytes metric (as asked about [here](https://forum.cockroachlabs.com/t/live-bytes-steadily-increasing/629)) and the increase in memory usage up to the RocksDB cache size (as asked about a number of times, but I don't have any examples offhand).

Would this fit in the FAQ, perhaps? Or should it be posted to StackOverflow?

**Comment by bdarnell** [comment] 2017-05-15 18:08
Duplicate of #957

**Closed by bdarnell** 2017-05-15 18:08 UTC
