### ISSUE TITLE
cliccl: add `load show backups` to display backup collection

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11493] opened 2021-09-08 19:26 UTC
PR: https://github.com/cockroachdb/cockroach/pull/61862

From release notes:
> Updated `load show` with `incremental` subcommand to display incremental backups. Users can list incremental backup paths of a full backup by running `cockroach load show incremental <backup_url>.` [#61862][#61862]

**Comment by kathancox** [comment] 2021-10-04 19:29
Closing as this is a duplicate of #11494

**Closed by kathancox** 2021-10-04 19:29 UTC
Labels: C-product-change, A-io, release-21.2
