### ISSUE TITLE
ui: Custom graph debug page

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#2669] opened 2018-03-08 21:05 UTC
PR: https://github.com/cockroachdb/cockroach/pull/23070

Low priority for 2.0 doc. Creating an issue just so I don't forget about it after 2.0 release

**Comment by jseldess** [comment] 2018-03-27 19:53
Duplicate of https://github.com/cockroachdb/docs/issues/2729.

**Closed by jseldess** 2018-03-27 19:53 UTC
