### ISSUE TITLE
need to curate release notes for changes in develop not yet in master (for beta-20161013)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/docs#716] opened 2016-10-05 15:56 UTC
This will be much more work than usually, so I created an extra issue.

**Comment by jseldess** [comment] 2016-10-06 15:30
@tschottdorf, @knz: I believe @bdarnell started this work last week: https://github.com/cockroachdb/docs/pull/694

**Comment by jseldess** [comment] 2016-10-10 16:36
This is duplicate of https://github.com/cockroachdb/cockroach/issues/9781

**Closed by jseldess** 2016-10-10 16:36 UTC
