### ISSUE TITLE
Capacity planning and troubleshooting

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2723] opened 2018-03-15 12:45 UTC
High level steps below.  More detail to be added

- run the workload at concurrency 1
collect performance data: throughput, response time
collect capacity data: CPU, RAM, Network bandwidth, Storage IOPS, Storage bandwidth, Storage capacity

- run the workload at least 2 other concurrency to construct the curve as below. More concurrency tests will produce more accurate prediction

![chart 3](https://user-images.githubusercontent.com/6315124/37463851-dbaf0824-282c-11e8-99b2-88c6c435415c.png)

- The capacity where the response time meet the SLA at various concurrent can be used to forecast

**Comment by jseldess** [comment] 2018-04-16 21:03
Capacity troubleshooting from:

Performance, availability, and stability issues can be caused by insufficient capacity.  

- "Because capacity is critical to availability ..."  Google SRE https://landing.google.com/sre/book.htm 
- https://github.com/cockroachdb/cockroach/issues/21416 has examples of issues capacity management can solve.

Initial suggestions below:

## Check Out of Capacity Conditions

First, check adequate capacity was available for the incident for the following components.

Type | Linux Command | what to look for
-- | -- | --
file system storage capacity | df -kh | file system at 99%
Storage IOPS / bandwidth capacity | sar -d | consistent non-zero values in avgqu-sz 
RAM capacity | sar -s | any non-zero value in kbswpused and %swpused
CPU capacity | sar  -q | consistent non-zero values in runq-sz 
Network capacity| sar -n ALL |  any non-zero value in rxerr/s, txerr/s, coll/s, rxdrop/s, txdrop/s, txcarr/s, rxfram/s, rxfifo/s, txfifo/s

## Check Near Out of Capacity Conditions

Type | Linux Command | what to look for
-- | -- | --
Storage bandwidth capacity | sar -d | consistently more than 80% or unusually high values in rd_sec/s and wr_sec/s (in 512 bytes sector thus not as accurate as iostat)  
Storage IOPS capacity | sar -d | consistently more than 1ms or unusually high values in await 
RAM capacity | sar -r | consistently more than 80% in %memused
CPU capacity | sar  -u | consistently less than 20% in %idle (ie:80% busy) 
Network capacity| sar -n ALL |  consistently more than 50% line capacity in rxkB/s or txkB/s

## Check for abnormal conditions

Historical measurements are required determine whether a metric is too high or too low.  Maintaining at least 1 month of historical data will be useful.

###  Linix sar in crontab

Enable sar data collected at 1-minute interval 

- Ubuntu
```
sudo bash
apt-get install sysstat
sed -ibak -e 's/ENABLED="false"/ENABLED="true"/g' /etc/default/sysstat
sed -ibak -e 's|5-55/10 \* \* \* \*|\* \* \* \* \*|g' /etc/cron.d/sysstat
```

**Comment by jseldess** [comment] 2018-04-16 21:06
This docs work should wait on this [related 2.1 roadmap work](https://github.com/cockroachdb/docs/issues/2931).

**Comment by jseldess** [comment] 2018-10-29 14:51
Based on feedback from @drewdeally, we don't yet have the data for this. Moving to Later.

**Comment by Amruta-Ranade** [comment] 2019-04-16 18:10
@robert-s-lee I addressed this issue here: https://www.cockroachlabs.com/docs/dev/cluster-setup-troubleshooting.html#capacity-planning-issues
PTAL and let me know if I can close this issue.

**Comment by drewdeally** [comment] 2019-04-17 01:43
These are to high and should be adjusted

**Comment by Amruta-Ranade** [comment] 2019-04-17 16:47
@drewdeally Can you share the correct values?

**Comment by taroface** [comment] 2020-10-06 18:03
Relates to #7818 and #8547.

**Comment by jseldess** [comment] 2021-11-27 13:36
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!

**Closed by jseldess** 2021-11-27 13:36 UTC
Labels: T-missing-info, A-io, O-sales-eng, P-2
