### ISSUE TITLE
Add step to install sqlalchemy driver to Connect to Your CockroachCloud Cluster Doc 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8267] opened 2020-09-10 16:05 UTC
Re: [Connect to Your CockroachCloud Cluster](https://cockroachlabs.com/docs//cockroachcloud/connect-to-your-cluster.html)

## Issue Description
sqlalchemy instructions on this page are missing the steps to install the driver. It only says to replace the `postgresql` url scheme with `cockroachdb`.

## Suggested Resolution 
Include the step to install sqlalchemy cockroachdb driver

```python
pip install sqlalchemy sqlalchemy-cockroachdb psycopg2
```

**Comment by jseldess** [comment] 2020-09-10 17:43
I think that's by design, based on this sentene:
> The following language-specific versions assume that you have installed the relevant client drivers.

But I could see the value in providing the install instructions so there's nowhere else to go to get through the tutorial.

**Comment by lnhsingh** [comment] 2021-02-26 01:54
Closing - as this is no longer relevant (sqlalchemy steps are no longer included on this doc)

**Closed by lnhsingh** 2021-02-26 01:54 UTC
Labels: A-cockroachcloud, C-improvement, O-sales-eng, T-missing-info
