### ISSUE TITLE
Update relevant docs with new permission schemes

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#8439] opened 2020-09-21 22:27 UTC
We introduced a few more role permissions to alleviate the need for admin across IMPORT, BACKUP, RESTORE and CHANGEFEED. We should embed these rules into the features themselves and point to the relevant `ALTER` or `GRANT` pages to give folks those roles to perform those tasks.

**DETAILS COMING AS I TEST THE DETAILS :D **

**Comment by lnhsingh** [comment] 2020-09-23 18:34
Closing because this is a dupe of #8432

**Closed by lnhsingh** 2020-09-23 18:34 UTC
Labels: A-io, C-improvement, O-product, P-1, T-follow-up
