### ISSUE TITLE
ui: link to "how is this metric calculated?" in tooltip goes to a 404

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/docs#9725] opened 2021-02-05 21:15 UTC
![image](https://user-images.githubusercontent.com/43821/107089621-ee10cd80-67cc-11eb-9aa3-b931e69d9136.png)

There is a link called "how is this metric calculated?" when hovering over the "capacity usage" column header on the cluster overview page. It goes to the following URI: https://www.cockroachlabs.com/docs/v20.2/admin-ui-cluster-overview.html#capacity-metrics

This URI appears to no longer exist. It appears that it was moved to here: https://www.cockroachlabs.com/docs/v20.2/ui-cluster-overview-page#capacity-metrics

Perhaps this was done during the docs site redesign? Please let me know if I've gotten something wrong here!

**Comment by jseldess** [comment] 2021-02-28 01:04
@taroface, we could put a redirect in place on our end for now, but fixing it in the product is best long-term.

**Comment by taroface** [comment] 2021-03-01 15:49
That URL was updated when renaming Admin UI -> DB Console. There's already a `redirect_from: admin-ui-cluster-overview-page.html` in place on the new page, so I assume the issue is that anchor links do not redirect. I'll file an issue to have this fixed in the UI.

**Comment by jseldess** [comment] 2021-03-01 15:57
Thanks, @taroface. Do you want to keep this open or can we close this once you've opened a cockroach issue?

**Comment by taroface** [comment] 2021-03-01 22:50
Filed https://github.com/cockroachdb/cockroach/issues/61295 and closing this now!

**Closed by taroface** 2021-03-01 22:50 UTC
Labels: A-observability, C-improvement
