### ISSUE TITLE
alternate CSV dump method

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1675] opened 2017-07-06 17:23 UTC
Re: [SQL Dump (Export)](https://cockroachlabs.com/docs//v1.0/sql-dump.html)

## Issue Description

Cockroach dump is a good way to get a dump of the schema.  For a dump of data, there are other performant methods such as below;

psql -t -F $'\t' --no-align -c "select * from tablename" > file.csv

cockroach sql --insecure --format tsv -e "select * from tablename" > file.csv

The CVS file can be loaded using the "copy tablename from stdin" commands.

## Suggested Resolution 

Does it make sense to document the other methods?

**Comment by jseldess** [comment] 2017-07-18 15:44
Duplicate of https://github.com/cockroachdb/docs/issues/1674

**Closed by jseldess** 2017-07-18 15:44 UTC
Labels: community
