### ISSUE TITLE
release-21.1: sql: Change to using a session variable instead of FORCE syntax for overriding zone configuration settings for MR databases and tables

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#10256] opened 2021-04-06 19:58 UTC
PR: https://github.com/cockroachdb/cockroach/pull/62119

From release notes:
> Reverted the change that added the `FORCE` keyword in [#61499][#61499] in favor of the `override_multi_region_zone_config` session variable.  [#62119][#62119] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment] 2021-05-19 19:22
Dupe of #10254 w.r.t. the `override_multi_region...` var -- and we don't need docs for the `FORCE` syntax, since that only flitted into existence briefly in a beta before being removed.

**Closed by rmloveland** 2021-05-19 19:22 UTC
Labels: A-multi-region, C-release-note
