### ISSUE TITLE
backupccl: allow restoring into multi-region databases

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11283] opened 2021-09-08 19:10 UTC
PR: https://github.com/cockroachdb/cockroach/pull/65015

From release notes:
> [`RESTORE`](../v21.2/restore.html) now supports restoring individual tables into a multi-region database. If the table being restored is also multi-region, `REGIONAL BY ROW` tables cannot be restored, and `REGIONAL BY TABLE` tables can only be restored if their localities match those of the database they're being restored into. [#65015][#65015] {% comment %}doc{% endcomment %}

**Comment by kathancox** [comment] 2021-10-06 21:11
Relates to #10937

**Comment by livlobo** [comment] 2021-10-08 19:47
This can be closed as a dupe of #10937

**Closed** 2021-11-03 20:08 UTC
Labels: C-product-change, A-io, release-21.2
