### ISSUE TITLE
cockroach sql defaults for interactive vs. non-interactive sessions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2263] opened 2017-12-06 15:45 UTC
Currently, only the interactive shell option defaults are documented: https://www.cockroachlabs.com/docs/stable/use-the-built-in-sql-client.html#sql-shell-options-changed-in-v1-1. These defaults are sometimes different for non-interactive sessions, i.e., executing from the command line or from a file.

cc @knz

**Comment by jseldess** [comment] 2017-12-06 15:46
Related issue: https://github.com/cockroachdb/docs/issues/2248

**Comment by lhirata** [comment] 2018-05-15 15:04
Closing this issue because it seems to be a dupe of #2397, which has been addressed by @rmloveland's #3031 (thanks!).

**Closed by lhirata** 2018-05-15 15:04 UTC
Labels: missing-info
