### ISSUE TITLE
sql: Recommendations to avoid OOM/workarounds for no admission control

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5665] opened 2019-10-22 15:39 UTC
A customer recently asked for documentation on how to prevent services from OOMing clusters. This would be solved by Admission Control but we haven't yet solved that feature. In the meantime, we could provide best practices and guidelines for how to setup services to prevent OOMs.

@BramGruneir can you link the zendesk and provide more details?

**Comment by ericharmeling** [comment] 2020-11-05 13:54
@BramGruneir @awoods187 

Do we still have zendesk links for this issue?

**Comment by awoods187** [comment] 2020-11-06 21:58
I'll defer to bram on Zendesk but we have tons of customers who run into this problem. @jordanlewis referenced this here recently too https://cockroachlabs.slack.com/archives/CV581CE78/p1604608729006500
also discussed https://github.com/cockroachdb/docs/issues/7221

**Comment by BramGruneir** [comment] 2020-11-07 13:49
I don't have any specific open zendesk issue.  But I'll ask our TSEs for input here.  They see it much more often.

**Comment by vy-ton** [comment] 2021-01-07 19:42
Duplicate of https://github.com/cockroachdb/docs/issues/7221

**Closed by vy-ton** 2021-01-07 19:42 UTC
Labels: A-sql, P-2
