### ISSUE TITLE
faq: release binaries don't work on Ubuntu 18.10

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#4035] opened 2018-11-13 20:09 UTC
If you try to run the binaries (2.1, but probably all the older ones too) on Ubuntu Cosmic, you get a message about libtinfo dynamic linking (@ajwerner maybe you can paste the exact error here).
That's kind of a biggie, and it might be happening on other new distros too (if they ship a new version of libtinfo (or is it ncurses?). We should call it out until we figure out what to do and ship a better binary.

Corresponding crdb issue:
https://github.com/cockroachdb/cockroach/issues/32281

People can build from source or install libtinfo5, I think.

cc @benesch

**Comment by jseldess** [comment] 2018-11-13 20:34
@andreimatei, our linux install page says the following currently:

> The CockroachDB binary for Linux requires `glibc` and `libncurses`, which are found by default on nearly all Linux distributions, with Alpine as the notable exception.

How might we expand that, in a concise way, to capture this issue? 

I also think we should add something about OS recommendations to our production checklist, @lhirata, so this ties into https://github.com/cockroachdb/docs/issues/3936.

**Comment by andreimatei** [comment] 2018-11-13 20:50
The best people to ask are @benesch and @knz. I think we should say that you want "ncurses version 5", and then we should provide a command line for installing it specifically on Ubuntu 18.10, where I think the package is called `libncurses5`.
And then there's a longer explanation about how this ncurses is what you want, even though I believe the error you get refers to `libtinfo`.
And, of course, the tragedy is that the "are found by default on nearly all Linux distributions" part seems to be becoming obsolete.

**Comment by jseldess** [comment] 2018-11-13 21:34
@lhirata, @andreimatei mentioned in another channel that this isn't urgent, since the Ubuntu version is new, so I think you can handle this as part of the production checklist work.

**Comment by knz** [comment] 2018-11-13 22:06
I think we need to provide guidance on the install page (in the list of prerequisites), not in a FAQ. The issue is already manifest in the latest CentOS release, and now Ubuntu, and I expect more in the next 6 months.

In all these cases there should be a compatibility packages users can install. This will help for the next 3-6 months. Then we'll have a more permanent fix in a later CockroachDB release.

**Comment by bdarnell** [comment] 2018-12-20 20:00
I think this was fixed in 2.1.3. @ajwerner can you confirm?

**Comment by ajwerner** [comment] 2018-12-20 20:02
Confirmed.

**Closed** 2019-01-08 21:16 UTC
Labels: A-ops&tools, C-known-limitation, C-missing-info, O-internal, P-1, ready
