### ISSUE TITLE
Update recommended production settings

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#965] opened 2017-01-05 15:03 UTC
In [recommended production settings](https://www.cockroachlabs.com/docs/recommended-production-settings.html), clarify information (or provide new information) on more discrete elements of a deployment like:

- Number of machines & disks
- Data center locations
- RAM & CPU

Also handle NTP in greater detail (#960)

**Comment by spencerkimball** [comment] 2017-04-03 23:00
Please include minimum recommended configuration as well.

**Comment by jseldess** [comment] 2017-04-12 01:39
Duplicate of #1132

**Closed by jseldess** 2017-04-12 01:39 UTC
Labels: enhancement
