### ISSUE TITLE
Gather debug details for down cluster

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1818] opened 2017-08-12 18:21 UTC
Document process of gathering debug details for an unavailable cluster. 

Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recQhY6Db9Qk0udSg

**Comment by sploiselle** [comment] 2017-08-14 03:16
@knz Are there any workarounds for this scenario we should document?

**Comment by petermattis** [comment] 2017-08-14 12:09
`debug zip` relies on the nodes in the cluster being up. Without the nodes being up, the manual option is to gather up the log files, though this doesn't capture the same info. I suppose we could provide a command to run on each node in the cluster, though gathering the same data as `debug zip` will be difficult as sometimes the info is spread across multiple nodes.

**Comment by knz** [comment] 2017-08-17 09:18
Also a lot of the info is stored in KV. We can't decode this data without waking up some of the layers in CockroachDB (Storage, KV, Txn, SQL), although we can achieve this even if server/gossip/replication is hosed.

**Comment by knz** [comment] 2017-08-17 09:18
@robert-s-lee please raise this issue to PM. This is a L-sized project actually and will need to be budgeted on the roadmap.

**Comment by nstewart** [comment] 2017-08-17 12:09
@dianasaur323 FYI as we lock down 1.2

**Comment by dianasaur323** [comment] 2017-08-17 13:28
I've been punting any work on debug zip in 1.2, but it would help to answer to following questions in order to prioritize.

1) How often have we actually used the debug zip and fixed issues for customers?
2) Is all the info necessary in the debug zip to fix issues? Or is exporting logs adequate?
3) We do have exporting admin UI graphs on the roadmap for 1.2. How would this work if the cluster is offline?

**Comment by knz** [comment] 2017-08-17 13:32
Point 1: I don't know. @a-robinson, @bdarnell?

Point 2: yes there is plenty in `debug zip` which is not in the logs. Schemas, network config, to name a few.  The list of things is listed at the beginning of https://www.cockroachlabs.com/docs/stable/debug-zip.html, see everything beyond "log files".

Point 3: good question. We can't!

**Comment by knz** [comment] 2017-08-17 13:34
Maybe this overall issue is strongly suggesting **we need new development to collect troubleshooting data out of an offline cluster**. The overall architecture of `debug zip`  is woefully inadequate to achieve this.

**Comment by dianasaur323** [comment] 2017-08-17 13:40
With admin UI graph export, that will also include the new /debug pages, so we would get configs there. Thank you for the link. The problem still remains that we can't get that data in offline mode.

In my opinion, getting some sort of solution for offline debugging is more important than exporting admin UI graphs, although the project does seem large. We have a meeting coming up later today to finalize scope, and I think we should bump this up in priority.

**Comment by knz** [comment] 2017-08-17 13:41
Yes I agree that enabling us to troubleshoot issues is probably higher priority than most other feature work.

**Comment by a-robinson** [comment] 2017-08-17 16:09
> How often have we actually used the debug zip and fixed issues for customers?

I've used debug zips to help with customer issues exactly twice. The logs are usually my main target, but other parts of it have been useful too (metrics, settings, ranges, etc.).

I'm not sure how much offline zips would give us, since if the problem is that a node can't start up, the log files (with some extra verbosity turned on if needed) would be my main resource for determining why it won't start up. And of course once it's started up, a debug zip could be generated.

Am I alone on this? What resources from an offline zip would someone use to debug startup problems?

**Comment by robert-s-lee** [comment] 2017-08-17 16:21
Gleaning info from the log files to figure out why the node cannot restart is what would be useful.  Was the troubleshooting done live or offline?  For customers C and A, we had web conferences for an hour looking at the logs among various nodes.  This will be an issue as we scale out.

**Comment by bdarnell** [comment] 2017-08-17 17:03
I've found log files useful but I don't think I've ever actually used a `debug zip`. 

We also have some offline diagnostic tools under the `cockroach debug` command (`cockroach debug range-descriptors` has been particularly helpful in the past), but I think just collecting log files would be enough of a starting point. (This doesn't even necessarily need to be built into the `cockroach` command, since the main thing to be done is for the user to `ssh` around and copy files).

**Comment by dianasaur323** [comment] 2017-08-17 17:48
Collecting notes from the brief discussion we just had about this line item - there may be a cockroach command we could run on a single node to pull in some of the local data. That being said, we could also document what to do when the cluster goes down. @jseldess

**Comment by jseldess** [comment] 2018-03-19 20:03
@dianasaur323, is this something we still want to document at some point? Should it be a priority for 2.1?

**Comment by dianasaur323** [comment] 2018-03-22 18:41
@jseldess We are making some fixes here, but no documentation needed. We are just going to be adding some additional metrics and making debug work when nodes are down.

**Comment by jseldess** [comment] 2018-03-22 19:29
Thanks, @dianasaur323. I'll close this then and open a new issue tracking the product work.

**Closed by jseldess** 2018-03-22 19:29 UTC
