### ISSUE TITLE
sqlccl: merge IMPORT and RESTORE jobs

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#2431] opened 2018-01-27 16:55 UTC
PR: https://github.com/cockroachdb/cockroach/pull/21490

**Comment by jseldess** [comment] 2018-02-14 20:52
Whoops. Dupe of https://github.com/cockroachdb/docs/issues/2511.

**Closed by jseldess** 2018-02-14 20:52 UTC
