### ISSUE TITLE
Improve search for original multi-region syntax

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/docs#11062] opened 2021-08-17 18:10 UTC
With the new multi-region abstractions set to be the primary view in our docs, our original multi-region syntax gets completely hidden and is no longer available when searching for keywords like "duplicate indexes", "geopartitioned leaseholders", "geopartitioned replicas", etc.  These searches typically take you to the release notes instead.  Can we make sure these searches at least take us to the proper docs?

![Screen Shot 2021-08-17 at 2 09 51 PM](https://user-images.githubusercontent.com/1087114/129778355-5cadb079-74c8-42b6-bcd2-23c0762a9bc1.png)

gz#9523

**Comment by awoods187** [comment] 2021-08-23 17:53
This is a dupe of https://github.com/cockroachdb/docs/issues/11056 that we intend to work through. Closing this in favor of the new one.

**Closed by awoods187** 2021-08-23 17:53 UTC
