### ISSUE TITLE
switch off of jekyll

### ISSUE THREAD

**Issue by benesch** [cockroachdb/docs#1716] opened 2017-07-17 13:57 UTC
It's become increasingly clear to me that we're at the limits of what Jekyll can handle for a documentation website. These are the big problems in my mind:

  * Cross-references are based on page names and section headers. Changing a page name or a section header will break every internal link that points at that page or section. We luckily use HTMLProofer to detect this breakage, but every HTMLProofer run takes about ~10m, so hunting down broken links requires a _long_ feedback cycle.

  * No support for book-like hierarchy, with chapters, sections, and subsections. I think @knz in particular would give anything for this layout (#1021).

  * No PDF output (#1484).

  * No plain text output (#1717)

  * Inconvenient interleaving of content and style. It's very confusing but also dangerous for maintainability to have HTML and CSS inline with the documentation text. This also contributes to the two problems immediately above.

  * Markdown is poorly-specified. Switching Markdown processors caused all sorts of unnecessary breakage because Markdown doesn't have a formal grammar to e.g. clarify when to indent a paragraph beneath a list or how many `|`s you need to start a table.

  * Slow compiles. The current site takes 8s to generate, and every new version will add about 4s to the build time. `jekyll serve --incremental` knocks that down to ~.2s, but only works in simple cases where you change e.g. `foo.md` and want to see `foo.html`. If you change a base layout, included file, or sidebar data, Jekyll will have to do a full rebuild, taking another 8s, if it even realizes that.

  * Unable to provide code examples with syntax highlighting inside a table. No multiple paragraphs.

  * Unable to display math equations (will be necessary once we start documenting resource costs)

Here's my proposal: use Sphinx. It neatly solves all my grievances. In order:

  * [Supports proper cross-references](http://www.sphinx-doc.org/en/stable/markup/inline.html#cross-referencing-syntax) that are independent of the page and section titles.

  * [Understands hierarchy.](http://www.sphinx-doc.org/en/stable/markup/toctree.html)

  * [Can generate PDFs.](http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.latex.LaTeXBuilder)

  * Supports inline math equations, inline block diagrams

  * Supports arbitrary markup inside table cells

  * Supports the definition of arbitrary new markup syntax that can be mapped to HTML/CSS using an *external* transformation.

  * [Also supports a well-specified markup language called reStructured Text.](http://www.sphinx-doc.org/en/stable/rest.html) (Sphinx actually supports multiple markup languages including markdown, AFAIK)

  * Compiles reasonably fast. The Python docs tree, which is much, much larger than ours (though not for long, I hope!), takes 2m to generate—but only the first time. After that, Sphinx is able to do an incremental build in ~7s, which includes properly regenerating dependent pages, like indices, and not just the one page that changed.

Changing our documentation generator would obviously have a massive impact on @jseldess, @sploiselle, and @Amruta-Ranade, and I don't mean to step on any toes! Just wanted to get a discussion started somewhere more permanent than Slack. I know Sphinx has been mentioned several times in passing, but I wanted to formalize the arguments for it.

The biggest downsides I see of a Sphinx transition:

  * Actually doing the transition. Oof. This smells like a post-1.2 project at _best_.

  * Disrupting everyone's workflow. rST, in particular, is a bit of a special snowflake. It's great once you know it, but it doesn't have the nearly non-existent learning curve that Markdown has.

FWIW, now that I've written all this up, I'm 👎 on switching to Hugo. Of the grievances above, I think it only fixes the slow compiles.

/cc @bdarnell @mjibson @knz

**Comment by dt** [comment] 2017-07-17 14:25
While we're considering big changes, I'd also submit for consideration:
serving the site using some very thin application server, rather than purely static files. 
This could be as simple as a [strawman] couple lines of node, map of paths to html files, just opens and serves file [/strawman] but it seems like it might be useful to have more control over our path routing (i.e. ability to serve 301s, 302, etc).

**Comment by jseldess** [comment] 2017-07-17 14:27
Thanks for starting this, @benesch! @knz and @bdarnell have both brought up a number of these points before, but it's really helpful to see the benefits of Sphinx enumerated. 

Longer-term, I agree that all of the above could cause be concerns. Short-term, I think the most immediate concern is Jekyll's lack of PDF output. 

Unfortunately, I do think this is at least post-1.1, given what's on our current plate. But let's please continue the discussion here.

**Comment by sploiselle** [comment] 2017-07-17 14:38
+1 on an rST-backed site generator.

**Comment by knz** [comment] 2017-07-17 14:38
I have modified the PR description at the top to add some considerations about the current problems.

I do not fully align on the description of the work to be done however. There are two separate sets of problems: those that will be solved by using a **different markup language** (even possibly using the same templating engine) and those that will be solved using a **different templating engine** (e.g. sphinx, possibly continuing to use markdown).

From the top of my head:

- cross-references, hierarchy, proper TOCs, these are problems solved by Sphinx, irrespective of the markup language. I guess we could bake a markdown extension to address the linking problem ourselves even without Sphinx  (although I am not keen on re-implementing this ourselves if an off-the-shelf solution does this right already)

- support for PDF output, plain text, math formulas, arbitrary markup in table cells, avoiding interleaving markup and HTML/CSS, these are problems caused specifcially by **markdown** and using a different markup format even without sphinx would move us forward on this.

**Comment by knz** [comment] 2017-07-17 14:42
Also, let's keep in mind very high that **this is not a discussion about moving away from text-based markup formats** and towards very noisy languages like TeX/SGML etc.

There is a large class of usability/productivity problems solved by text-based ("almost-WYSIWYG") markup, and we must not go on a path that would cause these problems to happen to us.

I have written before about different markup languages and what problems they solve, to conclude that rST and [Asciidoc](http://asciidoc.org/) in particular are superior to markdown: http://www.structured-commons.org/scep0106.html

AFAIK Sphinx also supports asciidoc :)

**Comment by bdarnell** [comment] 2017-07-17 17:27
@knz the sphinx/markdown integration extends markdown with support for [features including math rendering](http://recommonmark.readthedocs.io/en/latest/auto_structify.html#math-formula). On the other hand, sphinx's shorthand cross-reference syntax (plain backquotes) is one of the few places where I like RST better than markdown.

FWIW, I can't find any sphinx/asciidoc integration in a few minute's googling. I'm open to asciidoc-based solutions, but I'm not familiar with it at all. 

> support for PDF output, [...], these are problems caused specifcially by markdown and using a different markup format even without sphinx would move us forward on this.

I don't agree with this part. We could, for example, render markdown to pdf with `pandoc`. The problem is that to get *good* pdf output, we need something with more higher-level structure, not just converting our markdown to asciidoc. I'd put PDF output in the "solved by sphinx, irrespective of the markup language" bucket. 

I'm generally a fan of sphinx for our docs (and, I think, of moving from markdown to RST), although I must say that speed is probably not a reason to switch. Incremental builds with sphinx will generally be closer in speed to jekyll than hugo. And there's not a built-in equivalent to `jekyll serve --incremental`, so you have to kick off builds manually (there may be a third-party solution for this; it's been a while since i've looked for one).

**Comment by knz** [comment] 2017-07-17 17:35
@bdarnell 1) sphinx I recall supports "incremental builds" in the sense that you can serve the docs and have it re-build files on-demand when the underlying source changes 2) regarding conversion to PDF, my biggest gripe with the current approach is the interleaving of html/css/javascript with the doc source, which really complicates ("complicates" as in "sometimes makes it impossible") conversion to anything else than web pages.

**Comment by knz** [comment] 2017-10-26 23:40
I did some homework to match rST and markdown side-by-side:

- [rST vs markdown shootout in HTML](http://random.vodka-pomme.net/pub/markup.html).
- [same doc, rST sources](http://random.vodka-pomme.net/pub/markup.rst) - note, you couldn't make such a document in markdown, because markdown tables ... well...
- [if you want to regenerate the doc yourself, use this archive](http://random.vodka-pomme.net/pub/markup.zip).

**Comment by jseldess** [comment] 2018-04-17 17:00
In the 2.1 timeframe, we're exploring migrating docs from Jekyll to Hugo. I'll set up a meeting with people involved here to talk this through, but the high-level reasoning is here: https://github.com/cockroachdb/docs/issues/2941.

**Comment by jseldess** [comment] 2018-10-30 18:48
@mjibson has done most of the work to move us over to Hugo already. We'll do so in 2.2, probably Q4 2018. Closing this in favor of https://github.com/cockroachdb/docs/issues/2941.

**Closed by jseldess** 2018-10-30 18:48 UTC
Labels: A-docs-infrastructure
