### ISSUE TITLE
Consider updating the libraries used in Build a Go App with CockroachDB

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/docs#4971] opened 2019-06-25 15:57 UTC
A user recently suggested [here](https://gist.github.com/ajwerner/1b02589ab1cd83d95c7b116c90d5f83b#gistcomment-2952702) that we change our https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb.html from GORM to https://github.com/go-pg/pg/orm due what they report as performance problems with GORM. I don't know about the various tradeoffs but wanted to pass the message along.

Similarly, internally these days it seems that we prefer pgx to pq yet we suggest pq on the docs page.

**Comment by jseldess** [comment] 2019-06-25 16:53
Thanks for reporting, @ajwerner. @awoods187, @jordanlewis, who can help assess whether to switch to this other GO orm and driver? cc @rmloveland.

**Comment by rmloveland** [comment] 2019-08-08 20:22
Doubt we'll get to this in 19.2 milestone but agree we should consider it!

**Comment by awoods187** [comment] 2020-03-19 00:18
Closing this as a dupe of https://github.com/cockroachdb/docs/issues/6038

**Closed by awoods187** 2020-03-19 00:18 UTC
Labels: A-sql, C-improvement, O-external, P-2
