### ISSUE TITLE
investigate and document recommended TCP sysctls

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/docs#11716] opened 2021-09-19 21:32 UTC
The Linux kernel has a number of TCP stack settings that are configurable by the operator. Many of these can have a significant effect on CockroachDB performance and availability.

As an example, in https://github.com/cockroachdb/cockroach/issues/69893#issuecomment-921929021 we discussed how settings related to TCP retries such as `net.ipv4.tcp_retries2` or `net.ipv4.tcp_syn_retries` can significantly affect recovery times following a network or node outage.

There are also many settings that can significantly affect performance, including e.g. buffer sizes, queue sizes, initial window sizes, jumbo frames, and so on.

We should do a survey of relevant sysctls and write up some best practices for production systems, preferably backed by benchmarks. The same exercise would also be useful for disk IO sysctls.

**Comment by bdarnell** [comment] 2021-09-23 18:14
Duplicate of  #4209

**Closed by bdarnell** 2021-09-23 18:14 UTC
Labels: T-enhancement, P-2, C-doc-improvement, O-eng, A-ox-deploy-ops
