### ISSUE TITLE
Learner replicas

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4728] opened 2019-05-08 14:42 UTC
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec3BzN0RbEhDPHsP?blocks=hide
PM: @awoods187 
Eng: @danhhz, @tbg

**Comment by rmloveland** [comment] 2019-09-04 18:38
Dupe of #5274

**Closed by rmloveland** 2019-09-04 18:38 UTC
Labels: A-core, C-roadmap, P-1
