### ISSUE TITLE
New application testing best practices topic

### ISSUE THREAD

**Issue by ianjevans** [cockroachdb/docs#9679] opened 2021-02-01 17:54 UTC
Ian Evans (ianjevans) commented:

Part of phase 2.

Describe the best practices for testing an application, including DDL setup/cleanup.

Initial suggestions:

- `cockroachdb start-single-node --store=type=mem,size=10GiB` to start an in-memory cluster.
- Explore whether `DELETE FROM table WHERE true` is faster for removing inserted test demo, as opposed to `TRUNCATE table`.

gz#7480

**Comment by ericharmeling** [comment] 2021-11-18 17:44
This is effectively a duplicate of https://github.com/cockroachdb/docs/issues/10991

**Closed by ericharmeling** 2021-11-18 17:44 UTC
Labels: T-enhancement, G-sql, P-2
