### ISSUE TITLE
Update Hello World psycopg2 tutorial with new code changes

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/docs#8471] opened 2020-09-25 22:06 UTC
The code in the Hello World repo changed, so the docs pages should be updated as well. The psycopg2 maintainer we have been working with made the updates. The updates are mostly to make the code obey conventions better.

See: https://github.com/cockroachlabs/hello-world-python-psycopg2

**Comment by ericharmeling** [comment] 2020-10-12 16:50
Duplicate of https://github.com/cockroachdb/docs/issues/8277.

**Closed by ericharmeling** 2020-10-12 16:50 UTC
Labels: A-appdev, C-improvement
