### ISSUE TITLE
[Docs] Uplevel the language pages in the documentation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6255] opened 2020-01-06 15:22 UTC
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recBm7JyggA0iah6l

Description: Now, the docs repo provides one landing page each for Go, Java, and Python. These landing pages serve to coordinate and orient developers to the knowledge they need for each language. It will include all of the getting started guides for each supported ORM as well as any language specific tutorials.

Currently, developers have minimal information for how to program using their preferred application language with CockroachDB. We provide a sample toy application via a getting started guide for some, but not all of the supported ORMs.

Team: Andrew Woods, Rafi Shamim, Eric Harmeling, Richard Loveland

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/5626

**Comment by ericharmeling** [comment] 2020-02-24 17:59
Duplicate of #5626.

**Closed by ericharmeling** 2020-02-24 17:59 UTC
Labels: A-sql, C-docs-project, C-roadmap, X-duplicate
