### ISSUE TITLE
ui: fix styling for the expandable rows in the jobs table

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2524] opened 2018-02-14 20:29 UTC
PR: https://github.com/cockroachdb/cockroach/pull/22221

From release notes:
> Added an icon to indicate when descriptions in the Jobs table are shortened and expandable.

**Comment by Amruta-Ranade** [comment] 2018-03-08 18:40
Duplicate of #2421

**Closed by Amruta-Ranade** 2018-03-08 18:40 UTC
Labels: fixitday, product, ready
