### ISSUE TITLE
[Docs] Complete all removal of savepoints from remaining driver/ORM documentation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6057] opened 2019-11-26 22:05 UTC
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recT97d2o3ZqZEnWP

Description: CockroachDB docs examples now do not mention savepoints in their retry logic examples. 

Team: Andrew Woods, Rafi Shamim, Richard Loveland

**Comment by ericharmeling** [comment] 2020-02-24 21:28
Duplicate of #6271.

**Closed by ericharmeling** 2020-02-24 21:28 UTC
Labels: A-sql, C-docs-project, X-duplicate
