### ISSUE TITLE
FAQ: what happens if my clocks are not properly synchronized?

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1305] opened 2017-04-19 09:14 UTC
This question has been happening quite a lot. Variants:

- "your blog says that nodes must be synchronized so your consistency protocol works. How does it break if the clocks are wrong?"
- "the MaxOffset parameter is documented as ' *If observed clock offsets exceed this limit, inconsistency may result* ' - what kind of inconsistencies may result?"

Answer:

"
First of all, CockroachDB contains a protection mechanism. The inconsistency problem only starts to happen if the clock skew becomes larger than the configured MaxOffset parameter; however, a node also spontaneously shuts down if it detects its clock skew relative to other nodes becomes larger than MaxOffset/2. This means that nodes will shut down before inconsistencies occur in most cases. This is true especially in the case of slow clock drift, which is the natural situation on well-functioning hardware when NTP synchronization is not active. The only risk of clock skew affecting a CockroachDB cluster is sudden clock skew, when the clock jumps beyond MaxOffset before the node detects it. This is extremely unlikely, but can happen e.g. when running CockroachDB inside a VM and the VM hypervisor decides to migrate the VM to different hardware with a different time (i.e. both sides are not properly synchronized). In this case there can be a small time window between the moment a node's clock becomes unsynchronized and the moment where the node spontaneously aborts.

The guarantee you lose in this small time window is that a client may fail to read a value that was written before the read started. Reads could see stale data. Writes are mostly unaffected by clocks except to the extent that the application may write data derived from stale reads.
"

cc @bdarnell @spencerkimball

**Comment by knz** [comment] 2017-04-19 09:35
FIXME: clarify "reads could see stale data"

**Comment by bdarnell** [comment] 2017-04-19 17:25
Duplicate of #1303

**Closed by bdarnell** 2017-04-19 17:25 UTC
