### ISSUE TITLE
cliccl/load: update `load show` with `summary` subcommand to display backup meta information

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11491] opened 2021-09-08 19:26 UTC
PR: https://github.com/cockroachdb/cockroach/pull/61131

From release notes:
> Added `load show` args to display subset of backup metadata. Users can display subsets of metadata of a single manifest by using `load show files/descriptors/metadata/spans <backup_url>`. [#61131][#61131]

**Comment by kathancox** [comment] 2021-10-04 19:27
Closing as this is a duplicate of #11492

**Closed by kathancox** 2021-10-04 19:27 UTC
Labels: C-product-change, A-io, release-21.2
