### ISSUE TITLE
sql: Add support for JOIN LATERAL syntax

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5908] opened 2019-11-21 14:53 UTC
PR: https://github.com/cockroachdb/cockroach/pull/40945

From release notes:
> Added support for the `JOIN LATERAL` syntax. [#40945][#40945] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment] 2020-01-09 15:54
Duplicate of #5990.

**Closed by ericharmeling** 2020-01-09 15:54 UTC
Labels: A-sql, C-release-note
