### ISSUE TITLE
Tabs on install page unclear

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#1235] opened 2017-04-02 00:52 UTC
[A user on gitter](https://gitter.im/cockroachdb/cockroach?at=58e03ecbb52518ed4dce3977) found the installation instructions confusing, thinking that the "Download the binary" tab was the download link itself, styled as a button. We might want to change the styling (so that these boxes look more like tabs than buttons), or the text (this user suggested "Install the binary" instead of "Download the binary", although I'm not sure about this - installing a binary is a *step* in the build from source instructions, too). The "CockroachDB tarball for [OS]" link could also perhaps be made more prominent (more button-like?)

**Comment by kuanluo** [comment] 2017-06-27 19:40
We've found similar complains during user research. Here're a few low-cost improvement ideas: 

**If we keep the Mac/Linux/Windows selector:**
Option A: Tabs
![image](https://user-images.githubusercontent.com/1486483/27606481-85874f7a-5b4e-11e7-838e-08c765ee00df.png)

Option B: Segmented control
![image](https://user-images.githubusercontent.com/1486483/27606495-97ff8eec-5b4e-11e7-950d-0dd0ae933844.png)

**Alternatively**, we can combine the OS selector (it's defaulted anyways) with the install tabs into something like this to shorten the length of scroll on this page.
![image](https://user-images.githubusercontent.com/1486483/27606550-c762f412-5b4e-11e7-89b5-58fcf0a1a660.png)

What do you think, @bdarnell @jseldess?

**Comment by jseldess** [comment] 2017-06-27 19:50
Thanks, @kuanluo! I think i like option 2 best, but it'd be great to get more opinions. 

Another option would be to not have the second level "buttons/tabs", but rather to use a table of contents, like we have on most other pages, listing the install options. That would leave us just one filter level for OS.

**Comment by clickform** [comment] 2017-06-27 20:32
I'm into **Option A** as it has the best use of hierarchy and organization for the content than the other two options. As a note, the guide could use more direction to reduce some of the cognitive load of scanning around for the important details like install links. Here's a quick example ->
<img width="1143" alt="screen shot 2017-06-27 at 4 24 49 pm" src="https://user-images.githubusercontent.com/29442020/27608616-1c481ec4-5b56-11e7-8f16-42cdf66c8980.png">

**Comment by bdarnell** [comment] 2017-06-28 03:37
Do our analytics data tell us how often people switch the operating system to a page other than the default? As long as that is rarely used, I like the last option (2? C?). 

If we need to keep the OS selection very visible, I prefer option A. The subtly rounded corners of B don't do enough to make it look non-buttony.

**Comment by jseldess** [comment] 2017-06-28 11:12
I think we do have analytics on how often people change the OS. I'll look today. 

Reflecting more on this, I kind of like @josueeee's idea to frame it all as a sequence of steps. The concern about these appearing as buttons has only come up a few times, and the page is used very often, so I wonder if we're overengineering. I'll throw together a quick version of what the page would look like for real with steps and paste a screenshot here this morning.

**Comment by kuanluo** [comment] 2017-06-28 14:37
Good points, @bdarnell @josueeee! Let's take a look at the metrics first and go from there. Thank you, @jseldess for looking into it.

**Comment by jseldess** [comment] 2017-06-28 15:32
Here are the metrics:

![screen shot 2017-06-28 at 11 24 03 am](https://user-images.githubusercontent.com/15893490/27645557-5c778be4-5bf4-11e7-8761-0ff9fb4d9c82.png)

Event Action is the OS button clicked, and Operating System is the OS the user is on. Basically, it confirms that people are clicking on "OS" buttons different than the OS they are on. It makes sense to me that some people do this sometimes (when on Mac or Windows, you might be interested in details about install on Linux, especially if you're SSHing into a Linux server or something). These metrics also probably capture people clicking back and forth (thus the clicks on the Windows button by users already on Windows, etc.).

Unfortunately, we can't know if users are clicking so much because they think these are actual buttons that will do something (the original issue). So not sure what to do with the data. @bdarnell, what are you thoughts?

**Comment by jseldess** [comment] 2017-06-28 15:36
Actually, the metrics above include the OS buttons on this page as well: https://www.cockroachlabs.com/docs/recommended-production-settings.html#increase-the-file-descriptors-limit

The real numbers, just for the install page, are as follows:

![screen shot 2017-06-28 at 11 35 30 am](https://user-images.githubusercontent.com/15893490/27646204-0cfacafc-5bf6-11e7-97a3-85b965f5c093.png)

**Comment by kuanluo** [comment] 2017-06-28 17:13
Thanks for the data, @jseldess! One way to go about it is to implement Option A for both the OS as well as the download selector, and see how it affects analytics. 

![image](https://user-images.githubusercontent.com/1486483/27650611-6bfd7f56-5c03-11e7-8019-0beed6827272.png)

**Comment by couchand** [comment] 2017-06-28 18:15
I'll just throw in my two cents.  I like last option, for a few reasons:

- I don't think the purpose of this page is to advertise the platform support, so using that much real estate for OS logos seems like a waste.  It's much more important to advertise different ways of installing, since that's the real purpose of this page.
- I think it makes it clearer that both questions need to be answered before looking at the content.  The hierarchy isn't all that important here: if you care that it's hierarchical, you'll notice when you switch platforms that the install options change.
- I think tabs are confusing when they're in the middle of a page.  I think nested tabs are even more confusing.

**Comment by kuanluo** [comment] 2017-06-28 19:45
@couchand Just to clarify, you prefer Option C in the first batch of mocks? And I agree the nested tabs aren't ideal. 

Given that the "disguised tab as button" issue is relatively small (1 github issue and 2 users during interviews), I'd err on the side of making smaller cosmetic updates to begin with/test, and see where it gets us. 

Should we start by change download method buttons for tabs **only** and measure?

**Comment by couchand** [comment] 2017-06-28 20:21
@kuanluo yep Option C, my apologies, I can understand the confusion vs. the most recent mockup you posted.  I guess then the segmented control in Option B is a smaller change, but I'm not sure it really addresses the initial concern.  From where I'm sitting the issue is that it's not clear this is a page of instructions, and saving the screen real estate to make as many instructions as possible show up helps clarify that, and putting the OS and install types closer together would also assist.

Or maybe I'm just a tab hater.

**Comment by kuanluo** [comment] 2017-06-28 22:47
Ha, you might be, @couchand. ;) But that's totally allowed. 

From the researches we've done as well as anecdotally from our users, our install process is incredibly easy, which makes me hesitant to mess with what is working well. To properly introduce positive changes to the install page, it would take more resources on both design/engineering side. For a quick fix to address the original issue, I'm leaning towards **Option A to swap only the download option buttons for tabs** as the first step. 

We will watch the analytics results in a few weeks, but @couchand, if you volunteer to be the engineering partner on this, we can get results back much quicker. ;)

@jseldess, @bdarnell, what do you think?

**Comment by jseldess** [comment] 2017-06-29 02:46
I'm good with that, @kuanluo. I agree with @couchand that two levels of tabs feels strange. But I agree with you that, though the page isn't represented as a series of steps, like most of our other tasks/tutorials, it's proved to work very well until now, with some confusion over whether the filters are buttons here and there - the central issue. So let's see if removing that confusion, at least at the second level, makes a difference.

**Comment by kuanluo** [comment] 2017-06-29 15:15
I'm assigning this to DivOf. 👌

**Comment by jseldess** [comment] 2017-07-18 14:45
Fixed by https://github.com/cockroachdb/docs/pull/1711

**Closed by jseldess** 2017-07-18 14:45 UTC
Labels: community, enhancement, website
