### ISSUE TITLE
backupccl: allow appending incremental layers to backups

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6896] opened 2020-03-19 18:48 UTC
PR: https://github.com/cockroachdb/cockroach/pull/45255

From release notes:
> [`BACKUP`](../v20.1/backup.html) can be re-run with the same destination path to automatically append an incremental backup to that path. [#45255][#45255] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment] 2020-03-26 15:34
Closing - dupe of #6532

**Closed by lnhsingh** 2020-03-26 15:34 UTC
Labels: A-io, C-release-note
