### ISSUE TITLE
EXPLAIN ANALYZE Doc Update 

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#9483] opened 2021-01-25 15:40 UTC
Re: [EXPLAIN ANALYZE](https://cockroachlabs.com/docs//v20.2/explain-analyze.html)

## Issue Description

In the section DistSQL Plan Viewer, in the second row, it says the field is `<index>@<table>`; however, when using EXPLAIN ANALYZE it looks like it's `<table>@<index>`. See attached example. 
![image](https://user-images.githubusercontent.com/58006978/105727985-a4d19b80-5ef9-11eb-8fc3-c051be0ae8e6.png)

**Comment by ianjevans** [comment] 2021-04-05 22:56
Duplicate of #9154.

**Closed by ianjevans** 2021-04-05 22:56 UTC
Labels: A-sql, C-improvement, P-2
